create table if not exists public.vehicle_qr (
  code text primary key,
  phone text,
  push_subscription jsonb,
  active boolean not null default true,
  registered_at timestamptz,
  updated_at timestamptz not null default now()
);

create table if not exists public.call_requests (
  id bigint generated by default as identity primary key,
  qr_code text not null references public.vehicle_qr(code),
  request_type text not null check (request_type in ('move','emergency')),
  created_at timestamptz not null default now()
);

alter table public.vehicle_qr enable row level security;
alter table public.call_requests enable row level security;

-- 브라우저가 DB에 직접 접근하지 않고 Vercel API가 service role로 처리합니다.
-- 아래 100개 QR을 미등록 상태로 준비합니다.
insert into public.vehicle_qr(code, active)
select 'GJ-GK-' || lpad(n::text,3,'0') || '-STORE0001', true
from generate_series(1,100) n
on conflict (code) do nothing;
